### ISSUE TITLE
INIADのロゴを掲載する

### ISSUE THREAD

**Issue by satsatsuzuki** [citydx2022-059/iniad-fake-homepage#1]
公式ウェブサイトと同様にロゴを掲載することで、公式らしさを出す

**Comment by city-dx2022-063** [comment]
イメージとして、以前課題で使用したこちらのロゴでしょうか。
https://moocs-files.iniad.org/2018/CS2/web/iniad.png

**Comment by citydx2022-059** [comment]
コメントいただきありがとうございます。
以前の課題のように、ヘッダー左に組み込めないかなと考えまして、slackに書き込んだ分担として神田様にご対応いただけますと幸いです。

**Comment by city-dx2022-063** [comment]
承知しました。明日以降、作業に入ります。

**Comment by city-dx2022-063** [comment]
作業が完了しました。
