### ISSUE TITLE
スケジュールは表形式にするなどして見やすくする

### ISSUE THREAD

**Issue by citydx2022-024** [citydx2022-059/iniad-fake-homepage#10]

**Comment by citydx2022-059** [comment]
コメントいただきありがとうございます。
CSS内の#schedule、.iniad、.timeの調整は竹花様にお願いしたいと思います。

なお、表形式にすると設定が複雑になるため、現状のとおりリスト形式とし、cssにて文字色・文字サイズを調整することで見やすくなるのではないかな…と思います。

**Comment by citydx2022-059** [comment]
こちらに海野様もアサインさせていただきました。
CSS内の#schedule、.iniad、.timeの調整をお願いいたします。
設定としては、
・#scheduleのbackground-colorは#F2F2F2もしくは白
・.iniadのcolorは #4DADE5
　（INIADのロゴマークに使用されている水色をイメージ）
・.time のcolorは#444444
でいかがでしょうか。

なお、.timeのfont-sizeは現在30pxが指定されていますが、カットしてもいいような気がしています。

**Comment by citydx2022-061** [comment]
To：白柳様

アサインありがとうございます。
また、作業内容もご指示いただき、助かりますm(_ _)m

先ほど、#schedule, .iniad, .timeを調整し、GitにPushしました。
Live Serverで色を確認し、ご指示いただいた色に変更しました。

.time>font-sizeは、30pxですとバランスが悪いように感じまして、20pxに変更してみました。

以上、ご確認よろしくお願いいたします。
