### ISSUE TITLE
日本語ページ⇔英語ページへの変更ボタンを作成する

### ISSUE THREAD

**Issue by citydx2022-059** [citydx2022-059/iniad-fake-homepage#12]
元のCSS・HTMLファイルに「en」が用意されているので、サイドメニューの下段に「日本語／English」ボタンを入れるのはいかがでしょうか。
（イメージ図）
![Screenshot 2022-11-26 22 30 34](https://user-images.githubusercontent.com/118893017/204091439-1bceb260-bc7f-4ddc-9581-0a77f493c133.png)

**Comment by city-dx2022-063** [comment]
それでindex.htmlを含め、それぞれファイルが2つ有ったのですね。

**Comment by citydx2022-059** [comment]
サイトを表示するとChromeが翻訳してくれますが、それとは異なる内容だったので、英語ページを用意されているようです。

サイドバーの作成は少々骨が折れそうなので、ヘッダーに翻訳リンクを組み込もうかなと考えています。

**Comment by citydx2022-059** [comment]
完了しました。
