### ISSUE TITLE
背景色を変更する

### ISSUE THREAD

**Issue by satsatsuzuki** [citydx2022-059/iniad-fake-homepage#3]
公式サイトと同様に背景色は白（もしくは黒）に統一する

**Comment by city-dx2022-063** [comment]
公式サイトのイメージは、こちらでしょうか。
https://www.iniad.org/blog/2017/07/24/post-491/

**Comment by citydx2022-059** [comment]
コメントいただきありがとうございます。
背景色の設定は鈴木様にお願いしたいと思います。

**Comment by satsatsuzuki** [comment]
公式サイトのイメージは貼っていただいたものでイメージしておりました。
別途Slackでご指示いただいた通り、背景色は#ffffffに設定しております。
