### ISSUE TITLE
文字色を変更する

### ISSUE THREAD

**Issue by satsatsuzuki** [citydx2022-059/iniad-fake-homepage#4]
公式ウェブサイトとトーンをあわせるため、背景色が白なら黒、などモノトーン基調とする

**Comment by citydx2022-059** [comment]
コメントいただきありがとうございます。
CSS内のbody、h1、h2、h3の調整は鈴木様にお願いしたいと思います。

**Comment by satsatsuzuki** [comment]
body,h1,h2,h3の文字色を#444444に設定しました。
