### ISSUE TITLE
INIAD4つのコースのリンク先に各コースの説明を記載する

### ISSUE THREAD

**Issue by satsatsuzuki** [citydx2022-059/iniad-fake-homepage#6]
4つのコースが列挙されているだけで、それぞれどんなコースなのかがわからない。
公式ホームページhttps://www.toyo.ac.jp/academics/faculty/iniad/course/318706/へのリンクを張るか、説明文を記載する。

**Comment by citydx2022-059** [comment]
鈴木様、ありがとうございます。
本学のホームページからリンクを飛ばす方法で、白柳が作業したいと思います。

**Comment by citydx2022-059** [comment]
完了しました。
